package com.santiago.canchaapp.app.otros;

public enum FragmentTags {
    MIS_RESERVAS, MIS_ALQUILERES, REGISTRAR_CLUB, MAP_CLUB, CANCHA, REGISTRAR_CANCHA, CARGAR_FOTOS_CANCHA, MI_CLUB, BUSCAR_CANCHAS, CLUB
}
